In [1]:
import pandas as pd

At løbe 5 mph (12 min/mile) i 30 min koster 240 kalorier.

Kilde: Harvard University 
https://www.health.harvard.edu/diet-and-weight-loss/calories-burned-in-30-minutes-for-people-of-three-different-weights


Svarer til: 8 km/t koster 1.000 kJ.

In [2]:
# Konvertion fra kalorier til KJ:
cal_kj = 4.184

Jeg løber 10 km/t, hvilket er 25% hurtigere. Men forbrændning afhænger ikke udelukkende af hastighed, så jeg vælger kun at forøge forbrænding med 15%.

Det giver:

1154 kJ for 10 km/t i 30 min.

For træning med vægte og sjippetov:

600 kJ for 30 min.

In [3]:
vægt_df = pd.Series({"22.04.2024": 69, "24.06.2024": 67.4, "01.07.2024": 68.2, "12.07.2024": 67.9, "28.07.2024": 68.5
                     , "21.08.2024": 68.8, "12.09.2024": 66.9, "12.10.2024": 64.6, "19.10.2024": 64.3, "26.10.2024": 64.8
                     , "10.11.2024": 65.8, "21.12.2024": 65, "15.02.2025": 68, "16.02.2025": 66.2, "12.04.2025": 69.8})

vægt_df

22.04.2024    69.0
24.06.2024    67.4
01.07.2024    68.2
12.07.2024    67.9
28.07.2024    68.5
21.08.2024    68.8
12.09.2024    66.9
12.10.2024    64.6
19.10.2024    64.3
26.10.2024    64.8
10.11.2024    65.8
21.12.2024    65.0
15.02.2025    68.0
16.02.2025    66.2
12.04.2025    69.8
dtype: float64

In [4]:
vægt_df.describe()

count    15.000000
mean     67.013333
std       1.787203
min      64.300000
25%      65.400000
50%      67.400000
75%      68.350000
max      69.800000
dtype: float64

In [5]:
energy_data = pd.read_csv('energi.csv')

In [6]:
df = energy_data.copy()
df.rename(columns={'energi (kJ/100g)':'energi'
    , 'energi/portion':'portion', 'protein/100g':'protein'}, inplace=True)
df.sort_values(by='portion', ascending=False, inplace=True)

df

                  fødevare  energi  portion  protein
20                      is    1250     3000      3.5
19                svinekød    1100     1600     25.7
27               spaghetti    1480     1480     10.0
26                hvedemel    1450     1450     10.0
10                     ris    1477     1340      6.8
18            kyllingbryst     749     1123     31.0
39                    kalv     720     1080     24.4
2                havregryn    1528      900     11.7
43             proteindrik     247      809     24.0
42                 mandler    2423      800     21.2
30                   flute     800      800      8.0
40               karrysild    1275      750      5.1
36          søde kartofler     360      750      2.0
0                kartofler     322      700      2.0
23                 avocado     671      671      2.0
34              håndværker    1200      600      6.0
28               valnødder    2740      600     15.2
22                      æg     586      586     12.6
17                vindruer     288      576      0.7
24         Cultura yoghurt     285      570      4.2
13                   banan     372      558      1.1
12                     tun     552      552     28.0
31               roastbeef    1089      550     28.9
45           græsk yoghurt     514      514      4.2
6                 kikærter     491      491      6.8
9             cremefraiche     785      490      3.1
29                   Cocio     197      480      3.9
8                   makrel     656      410     14.0
38  cheasy protein yoghurt     200      400      6.5
21               BBQ sauce     772      378      1.6
44                    skyr     233      348      8.6
25           appelsinjuice     162      310      0.7
14                appelsin     197      300      0.9
37                broccoli     142      300      2.8
35             leverpostej    1000      275     11.0
15                 gulerod     173      250      0.9
1                  rugbrød     900      250      6.4
46                 edamame     507      250     11.9
33                  blåbær     204      240      0.7
41      kyllingleverpostej     725      218     11.0
16                   agurk      67      200      0.7
11                 rosiner    1433      200      1.0
5            kaffe m. mælk     267      178      3.4
4                     mælk     267      178      3.4
3                     majs     354      115      2.8
32                   rejer     397      100     20.3
7               mayonnaise    1522       67      0.7

In [7]:
metab = 10_500

def e(food: str):
    return df.loc[df['fødevare'] == food, 'portion'].values[0]

In [8]:
dinner_meat = sum([e('rugbrød')*2, e('makrel')*3, e('mayonnaise')
    , e('appelsin'), e('banan'), e('gulerod')*4
    , e('kyllingbryst'), e('agurk')*2, e('majs')*2
    , e('cremefraiche'), e('tun')/3
    , e('kaffe m. mælk')*6, 
    ])

normal_day = sum([e('rugbrød')*2, e('æg'), e('avocado'), e('mayonnaise') * 2
    , e('banan'), e('gulerod')*3, e('tun')/3, e('cremefraiche')
    , e('agurk'), e('majs'), e('kikærter'), e('kaffe m. mælk')*5
    , e('vindruer') 
    ])

home_day = sum([e('rugbrød')*2, e('æg'), e('avocado'), e('mayonnaise') * 2
    , e('banan'), e('gulerod')*4, e('tun')/3, e('cremefraiche')
    , e('agurk'), e('majs')*2, e('kikærter'), e('kaffe m. mælk')*5
    , e('vindruer') 
    ])

work = sum([e('kaffe m. mælk')*3, e('rugbrød'), e('flute'), e('mayonnaise')
    , e('roastbeef'), e('svinekød'), e('cremefraiche'), e('kartofler'), e('rugbrød')*2, e('avocado')
    , e('æg'), e('rejer'), e('mayonnaise')*2, e('Cocio')*3, e('vindruer'), e('majs')
    ])

In [9]:
work_fasting = sum([e('kaffe m. mælk')*4, e('mandler'), e('banan')*2, e('agurk')*2, e('kartofler'),
    e('kalv'), e('gulerod')*4])

work_fasting_small = sum([e('kaffe m. mælk')*4, e('mandler'), e('banan')*3, e('gulerod')*3,
    e('rugbrød')*2, e('avocado'), e('mayonnaise'), e('rejer'), e('karrysild'), e('blåbær')])

In [10]:
diet_list = [dinner_meat, normal_day, home_day, work, work_fasting, work_fasting_small]
diet_names = ['dinner_meat', 'normal_day', 'home_day', 'work', 'work_fasting', 'work_fasting_small']
metab_covered = [round(diet/metab,2) for diet in diet_list]
diet_table = pd.DataFrame({'diet': diet_names, 'energy': diet_list, 'metab_covered': metab_covered})

diet_table

                 diet  energy  metab_covered
0         dinner_meat  7150.0           0.68
1          normal_day  6145.0           0.59
2            home_day  6510.0           0.62
3                work  9113.0           0.87
4        work_fasting  5808.0           0.55
5  work_fasting_small  6264.0           0.60

In [11]:
today = sum([e('rugbrød')*4, e('æg')*1, e('avocado'), e('mayonnaise') * 2
    , e('banan'), e('gulerod')*3, e('tun')/3, e('cremefraiche')
    , e('agurk'), e('majs'), e('kaffe m. mælk')*5
    , e('blåbær'), e('makrel'), e('rejer')
    ])

print(today)
print(today/metab)

6328.0
0.6026666666666667

In [12]:
today2 = sum([e('mandler')*1.5, e('karrysild'), e('kyllingleverpostej')*2, e('gulerod')*4
    , e('kaffe m. mælk')*5, e('banan')*2, e('proteindrik')*2, e('rugbrød')*3])

print(today2)

7760.0

In [13]:
today3 = sum([e('mandler'), e('proteindrik')*2, e('kaffe m. mælk')*5, e('gulerod')*2
    , e('kikærter')*2, e('græsk yoghurt'), e('skyr'), e('Cultura yoghurt')*0.5, e('edamame')
    , e('majs')])

print(today3)

6302.0